version: '3.8'

services:
  backend:
    build: ./backend
    container_name: vikdev-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./backend/.env
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend-network

  # Cloudflare tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: vikdev-tunnel
    command: tunnel --config /etc/cloudflared/config.yml run vikdev-api
    volumes:
      - ~/.cloudflared:/etc/cloudflared:ro
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info", "vikdev-api"]
      interval: 60s
      timeout: 10s
      retries: 3

networks:
  backend-network:
    driver: bridge